import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const animeCharacters = [
    {
    name: 'Cleopatra VII',
    description: 'Last active ruler of the Ptolemaic Kingdom of Egypt.',
    overview: 'Known for her political acumen and romantic alliances with Julius Caesar and Mark Antony.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Cleopatra-VII-Philopator.jpg',
    gender: 'Female',
    category: 'Historical',
  },
  {
    name: 'Julius Caesar',
    description: 'Roman general and statesman who played a critical role in the fall of the Roman Republic.',
    overview: 'Dictator of Rome, whose assassination led to the rise of the Roman Empire.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Julius_Caesar_Bust.jpg',
    gender: 'Male',
    category: 'Historical',
  },
  {
    name: 'Joan of Arc',
    description: 'French heroine and Roman Catholic saint.',
    overview: 'Led French forces to key victories during the Hundred Years’ War before being martyred.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Joan_of_Arc_miniature_graded.jpg',
    gender: 'Female',
    category: 'Historical',
  },
  {
    name: 'Genghis Khan',
    description: 'Founder and first Great Khan of the Mongol Empire.',
    overview: 'United the Mongol tribes and conquered vast parts of Asia and Europe.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/YuanEmperorAlbumGenghisPortrait.jpg',
    gender: 'Male',
    category: 'Historical',
  },
  {
    name: 'Abraham Lincoln',
    description: '16th President of the United States.',
    overview: 'Led the U.S. during the Civil War and abolished slavery with the Emancipation Proclamation.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg',
    gender: 'Male',
    category: 'Historical',
  },
  {
    name: 'Queen Victoria',
    description: 'Queen of the United Kingdom of Great Britain and Ireland.',
    overview: 'Ruled during the Victorian Era, a period of industrial and cultural growth.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Queen_Victoria_by_Bassano.jpg',
    gender: 'Female',
    category: 'Historical',
  },
  {
    name: 'Winston Churchill',
    description: 'British Prime Minister during World War II.',
    overview: 'Led Britain through WWII and delivered famous speeches of resilience.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Sir_Winston_Churchill_-_19086236948.jpg',
    gender: 'Male',
    category: 'Historical',
  },
  {
    name: 'Florence Nightingale',
    description: 'Founder of modern nursing.',
    overview: 'Revolutionized medical care during the Crimean War.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Florence_Nightingale_%28H_Hering_NPG_x82368%29.jpg',
    gender: 'Female',
    category: 'Historical',
  },
  {
    name: 'Alexander the Great',
    description: 'King of Macedonia and one of history’s greatest military minds.',
    overview: 'Conquered much of the known world by age 30.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/AlexanderTheGreat_Bust.jpg',
    gender: 'Male',
    category: 'Historical',
  },
  {
    name: 'Leonardo da Vinci',
    description: 'Italian polymath of the Renaissance.',
    overview: 'Famous for artworks like the Mona Lisa and inventions far ahead of his time.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg/800px-Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg',
    gender: 'Male',
    category: 'Historical',
  },
 {
    name: 'Albert Einstein',
    description: 'Renowned theoretical physicist known for the theory of relativity.',
    overview: 'Einstein revolutionized our understanding of space, time, and energy.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Albert_Einstein_1921.jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Mahatma Gandhi',
    description: 'Leader of India\'s non-violent independence movement.',
    overview: 'Gandhi is known for his philosophy of nonviolent resistance and his pivotal role in India\'s struggle for independence.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/3/39/Mahatma_Gandhi_1942.jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Marie Curie',
    description: 'Pioneer in radioactivity research and first woman to win a Nobel Prize.',
    overview: 'Curie\'s groundbreaking work on radioactivity led to the development of X-ray machines.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Marie_Curie_c1920.jpg',
    gender: 'Female',
    category: 'Real_Person',
  },
  {
    name: 'Martin Luther King Jr.',
    description: 'Civil rights leader advocating for racial equality in the U.S.',
    overview: 'King\'s leadership in the American civil rights movement earned him the Nobel Peace Prize.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/King%2C_Martin_Luther%2C_Jr..jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Leonardo da Vinci',
    description: 'Polymath known for art, science, and engineering.',
    overview: 'Renowned for masterpieces like the Mona Lisa and his revolutionary inventions.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Frida Kahlo',
    description: 'Mexican painter celebrated for her self-portraits and works inspired by nature.',
    overview: 'Kahlo’s art explores identity, postcolonialism, and the human experience.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Frida_Kahlo%2C_1932%2C_by_Guillermo_Kahlo.jpg',
    gender: 'Female',
    category: 'Real_Person',
  },
  {
    name: 'Nelson Mandela',
    description: 'Anti-apartheid revolutionary and former President of South Africa.',
    overview: 'Mandela led the struggle against apartheid and became South Africa\'s first black president.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Nelson_Mandela_1991.jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Amelia Earhart',
    description: 'Aviation pioneer and first female aviator to fly solo across the Atlantic Ocean.',
    overview: 'Earhart broke records in aviation, symbolizing courage and the advancement of women in the field.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Amelia_Earhart_in_1935.jpg',
    gender: 'Female',
    category: 'Real_Person',
  },
  {
    name: 'Stephen Hawking',
    description: 'Theoretical physicist known for his work on black holes and cosmology.',
    overview: 'Hawking’s research into the nature of black holes and the cosmos made him a scientific icon.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Stephen_Hawking_2015.jpg',
    gender: 'Male',
    category: 'Real_Person',
  },
  {
    name: 'Malala Yousafzai',
    description: 'Education activist and youngest Nobel Prize laureate.',
    overview: 'Malala has become a global advocate for girls’ education and women’s rights.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Malala_Yousafzai_2015.jpg',
    gender: 'Female',
    category: 'Real_Person',
  },
    {
    name: 'Mario',
    description: 'Iconic plumber from Nintendo\'s "Super Mario" series.',
    overview: 'Mario is a courageous adventurer who battles enemies to rescue Princess Peach.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Mario_%28Super_Mario%29.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Lara Croft',
    description: 'Adventurer in the "Tomb Raider" franchise.',
    overview: 'Lara Croft is an explorer and archaeologist, renowned for her action-packed adventures.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Lara_Croft%2C_Tomb_Raider.png',
    gender: 'Female',
    category: 'Game',
  },
  {
    name: 'Master Chief',
    description: 'Super-soldier protagonist of the "Halo" series.',
    overview: 'Master Chief is humanity\'s last hope against the alien Covenant and other threats.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Master_Chief_Halo.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Link',
    description: 'Hero of the "Legend of Zelda" series.',
    overview: 'Link is a courageous hero who embarks on quests to save Princess Zelda and the kingdom of Hyrule.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Link_%28Legend_of_Zelda%29.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Solid Snake',
    description: 'Stealth operative in the "Metal Gear Solid" series.',
    overview: 'Solid Snake is a legendary soldier known for his stealth abilities and tactical genius.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Solid_Snake_Metal_Gear_Solid_4.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Kratos',
    description: 'Spartan warrior in "God of War."',
    overview: 'Kratos is a god-slaying warrior seeking redemption and a better life for his son.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Kratos_God_of_War.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Samus Aran',
    description: 'Bounty hunter in "Metroid."',
    overview: 'Samus Aran is an intergalactic bounty hunter battling space pirates and hostile alien species.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Samus_Aran.png',
    gender: 'Female',
    category: 'Game',
  },
  {
    name: 'Geralt of Rivia',
    description: 'Monster hunter in "The Witcher" series.',
    overview: 'Geralt of Rivia is a professional monster hunter with a strong moral code and incredible combat skills.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Geralt_of_Rivia_%28The_Witcher%29.png',
    gender: 'Male',
    category: 'Game',
  },
  {
    name: 'Ellie',
    description: 'Survivor in "The Last of Us."',
    overview: 'Ellie is a tough survivor in a post-apocalyptic world, navigating through dangerous enemies and moral challenges.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Ellie_%28The_Last_of_Us%29.png',
    gender: 'Female',
    category: 'Game',
  },
  {
    name: 'Cloud Strife',
    description: 'Mercenary in "Final Fantasy VII."',
    overview: 'Cloud Strife is a former soldier turned mercenary, trying to unravel his past and save the planet.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Cloud_Strife_Artwork.png',
    gender: 'Male',
    category: 'Game',
  },
   {
    name: 'Gandalf',
    description: 'Wizard from J.R.R. Tolkien\'s Middle-earth.',
    overview: 'Gandalf is a wise and powerful wizard who helps guide the Fellowship of the Ring.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Gandalf%2C_the_Grey.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
  {
    name: 'Daenerys Targaryen',
    description: 'Mother of Dragons in "Game of Thrones."',
    overview: 'Daenerys is a Targaryen princess with dragons, seeking to reclaim the Iron Throne.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Daenerys_Targaryen.jpg',
    gender: 'Female',
    category: 'Fantasy',
  },
  {
    name: 'Legolas',
    description: 'Elven archer in "The Lord of the Rings."',
    overview: 'Legolas is a skilled elf archer and member of the Fellowship, known for his agility and precision.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Legolas_-_Orlando_Bloom.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
  {
    name: 'Albus Dumbledore',
    description: 'Headmaster in "Harry Potter."',
    overview: 'Albus Dumbledore is the wise and powerful headmaster of Hogwarts School of Witchcraft and Wizardry.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Albus_Dumbledore.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
  {
    name: 'Arya Stark',
    description: 'Skilled assassin in "Game of Thrones."',
    overview: 'Arya Stark is a young, skilled fighter who trains as an assassin, seeking revenge against those who wronged her family.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Arya_Stark.jpg',
    gender: 'Female',
    category: 'Fantasy',
  },
  {
    name: 'Drizzt Do\'Urden',
    description: 'Drow ranger in "Forgotten Realms."',
    overview: 'Drizzt Do\'Urden is a drow elf who rejects the evil ways of his people and becomes a hero in the Underdark.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Drizzt_DoUrden.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
  {
    name: 'Korra',
    description: 'Avatar in "The Legend of Korra."',
    overview: 'Korra is the Avatar, a powerful bender who must maintain balance in the world.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Korra.jpg',
    gender: 'Female',
    category: 'Fantasy',
  },
  {
    name: 'San',
    description: 'Wolf girl in "Princess Mononoke."',
    overview: 'San, also known as Princess Mononoke, is a human girl raised by wolves who fights to protect the forest spirits.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/San_princess_mononoke.jpg',
    gender: 'Female',
    category: 'Fantasy',
  },
  {
    name: 'Geralt of Rivia',
    description: 'Witcher in Andrzej Sapkowski\'s series.',
    overview: 'Geralt of Rivia is a monster hunter with supernatural abilities, navigating a world of magic and danger.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Geralt_of_Rivia_-_The_Witcher.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
  {
    name: 'Elric of Melniboné',
    description: 'Albino sorcerer and anti-hero.',
    overview: 'Elric of Melniboné is an albino sorcerer, known for his cursed sword and tragic fate.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Elric_of_Melnibone.jpg',
    gender: 'Male',
    category: 'Fantasy',
  },
    {
    name: 'Beyoncé',
    description: 'Singer, songwriter, and actress.',
    overview: 'Beyoncé is known for her powerful voice and is a global pop culture icon.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Beyoncé_2018_%28cropped%29.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
  {
    name: 'Dwayne "The Rock" Johnson',
    description: 'Actor and former professional wrestler.',
    overview: 'Dwayne Johnson, known as The Rock, is a former wrestler turned actor with major roles in Hollywood.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Dwayne_Johnson_in_2020.jpg',
    gender: 'Male',
    category: 'Celebrity',
  },
  {
    name: 'Taylor Swift',
    description: 'Singer-songwriter known for narrative songs.',
    overview: 'Taylor Swift is famous for her storytelling lyrics and has earned numerous Grammy awards.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Taylor_Swift_2019_by_Glenn_Francis.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
  {
    name: 'Leonardo DiCaprio',
    description: 'Academy Award-winning actor.',
    overview: 'Leonardo DiCaprio is known for his exceptional performances in films like Titanic and Inception.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Leonardo_DiCaprio_2016.jpg',
    gender: 'Male',
    category: 'Celebrity',
  },
  {
    name: 'Oprah Winfrey',
    description: 'Talk show host and philanthropist.',
    overview: 'Oprah Winfrey is a media mogul, known for her influential talk show and philanthropic efforts.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Oprah_Winfrey_2014.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
  {
    name: 'Rihanna',
    description: 'Singer and fashion entrepreneur.',
    overview: 'Rihanna is a global pop star known for her chart-topping hits and Fenty fashion line.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Rihanna_2015.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
  {
    name: 'Tom Hanks',
    description: 'Versatile actor known for numerous roles.',
    overview: 'Tom Hanks is an actor beloved for his roles in Forrest Gump, Cast Away, and more.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Tom_Hanks_2019.jpg',
    gender: 'Male',
    category: 'Celebrity',
  },
  {
    name: 'Lady Gaga',
    description: 'Singer and actress known for her versatility.',
    overview: 'Lady Gaga is known for her bold fashion choices and iconic music hits like "Bad Romance" and "Shallow."',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Lady_Gaga_2019.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
  {
    name: 'Brad Pitt',
    description: 'Actor and film producer.',
    overview: 'Brad Pitt is an actor and producer with an extensive filmography, including roles in Fight Club and Once Upon a Time in Hollywood.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/7/71/Brad_Pitt_2019.jpg',
    gender: 'Male',
    category: 'Celebrity',
  },
  {
    name: 'Ariana Grande',
    description: 'Singer and actress.',
    overview: 'Ariana Grande is a pop singer and actress with a remarkable vocal range and numerous hit songs.',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Ariana_Grande_2019.jpg',
    gender: 'Female',
    category: 'Celebrity',
  },
   {
    name: 'Aria Windrunner',
    description: 'Elven ranger with a mysterious past.',
    overview: 'Aria is a skilled archer, with a deep connection to nature and the magical forces of her realm.',
    avatar: 'https://example.com/aria_windrunner_avatar.png',
    gender: 'Female',
    category: 'Custom',
  },
  {
    name: 'Thorne Ironfist',
    description: 'Dwarven blacksmith turned warrior.',
    overview: 'Thorne is a formidable fighter and master blacksmith, seeking vengeance for his lost clan.',
    avatar: 'https://example.com/thorne_ironfist_avatar.png',
    gender: 'Male',
    category: 'Custom',
  },
  {
    name: 'Selene Nightshade',
    description: 'Human sorceress seeking forbidden knowledge.',
    overview: 'Selene delves into dark magic in search of immortality, becoming a powerful and feared mage.',
    avatar: 'https://example.com/selene_nightshade_avatar.png',
    gender: 'Female',
    category: 'Custom',
  },
  {
    name: 'Kael Stormborn',
    description: 'Dragonkin mage mastering elemental powers.',
    overview: 'Kael is the last of his kind, a dragonkin born with the ability to control fire, ice, and lightning.',
    avatar: 'https://example.com/kael_stormborn_avatar.png',
    gender: 'Male',
    category: 'Custom',
  },
  {
    name: 'Lyra Moonshadow',
    description: 'Halfling rogue with a heart of gold.',
    overview: 'Lyra is a mischievous but kind-hearted rogue, always willing to help those in need despite her kleptomaniac tendencies.',
    avatar: 'https://example.com/lyra_moonshadow_avatar.png',
    gender: 'Female',
    category: 'Custom',
  },
  {
    name: 'Darius Flameheart',
    description: 'Human paladin on a quest for redemption.',
    overview: 'Darius seeks to atone for past sins, wielding a flaming sword and seeking to protect the innocent.',
    avatar: 'https://example.com/darius_flameheart_avatar.png',
    gender: 'Male',
    category: 'Custom',
  },
  {
    name: 'Elandra Whisperwind',
    description: 'Elf druid protecting ancient forests.',
    overview: 'Elandra is a wise elf who communicates with the spirits of the forest, determined to protect nature from destruction.',
    avatar: 'https://example.com/elandra_whisperwind_avatar.png',
    gender: 'Female',
    category: 'Custom',
  },
  {
    name: 'Garrick Stonebreaker',
    description: 'Orc warrior challenging tribal traditions.',
    overview: 'Garrick defies the oppressive traditions of his tribe, seeking peace and unification with other races.',
    avatar: 'https://example.com/garrick_stonebreaker_avatar.png',
    gender: 'Male',
    category: 'Custom',
  },
  {
    name: 'Isolde Frostveil',
    description: 'Ice sorceress from the northern realms.',
    overview: 'Isolde wields the power of winter, controlling blizzards and ice to protect her homeland from invaders.',
    avatar: 'https://example.com/isolde_frostveil_avatar.png',
    gender: 'Female',
    category: 'Custom',
  },
  {
    name: 'Riven Blackthorn',
    description: 'Cursed knight seeking to break his fate.',
    overview: 'Riven is a knight bound by an ancient curse, struggling to overcome the darkness that threatens to consume him.',
    avatar: 'https://example.com/riven_blackthorn_avatar.png',
    gender: 'Male',
    category: 'Custom',
  },
   {
    name: 'Zeus',
    description: 'King of the Greek gods, ruler of the sky and thunder.',
    overview: 'Zeus is the leader of the Olympian gods and wields the powerful thunderbolt.',
    avatar: 'https://example.com/zeus_avatar.png',
    gender: 'Male',
    category: 'Mythological',
  },
  {
    name: 'Hera',
    description: 'Queen of the Greek gods, goddess of marriage and family.',
    overview: 'Hera is Zeus’s wife and protector of women, marriage, and birth.',
    avatar: 'https://example.com/hera_avatar.png',
    gender: 'Female',
    category: 'Mythological',
  },
  {
    name: 'Thor',
    description: 'Norse god of thunder, storms, and strength.',
    overview: 'Thor is known for wielding the hammer Mjolnir and is a protector of gods and humans.',
    avatar: 'https://example.com/thor_avatar.png',
    gender: 'Male',
    category: 'Mythological',
  },
  {
    name: 'Athena',
    description: 'Greek goddess of wisdom, warfare, and strategy.',
    overview: 'Athena is the daughter of Zeus, a warrior goddess known for her intellect and fairness.',
    avatar: 'https://example.com/athena_avatar.png',
    gender: 'Female',
    category: 'Mythological',
  },
  {
    name: 'Odin',
    description: 'King of the Norse gods, god of wisdom and war.',
    overview: 'Odin sacrificed his eye to gain wisdom and is known for his mastery of magic and runes.',
    avatar: 'https://example.com/odin_avatar.png',
    gender: 'Male',
    category: 'Mythological',
  },
  {
    name: 'Medusa',
    description: 'A Gorgon with snakes for hair, whose gaze turns people to stone.',
    overview: 'Medusa was once a beautiful maiden, cursed by Athena and turned into a monster.',
    avatar: 'https://example.com/medusa_avatar.png',
    gender: 'Female',
    category: 'Mythological',
  },
  {
    name: 'Hades',
    description: 'Greek god of the underworld and ruler of the dead.',
    overview: 'Hades governs the realm of the dead and is often depicted with a dark and stern nature.',
    avatar: 'https://example.com/hades_avatar.png',
    gender: 'Male',
    category: 'Mythological',
  },
  {
    name: 'Anubis',
    description: 'Ancient Egyptian god of funerary rites and the afterlife.',
    overview: 'Anubis is depicted with a jackal head and is known as the protector of graves and guide to the afterlife.',
    avatar: 'https://example.com/anubis_avatar.png',
    gender: 'Male',
    category: 'Mythological',
  },
  {
    name: 'Isis',
    description: 'Egyptian goddess of magic, motherhood, and fertility.',
    overview: 'Isis is revered for her wisdom and ability to bring healing and protection.',
    avatar: 'https://example.com/isis_avatar.png',
    gender: 'Female',
    category: 'Mythological',
  },
  {
    name: 'Persephone',
    description: 'Greek goddess of the underworld and spring.',
    overview: 'Persephone was abducted by Hades but later became the queen of the underworld, symbolizing rebirth and growth.',
    avatar: 'https://example.com/persephone_avatar.png',
    gender: 'Female',
    category: 'Mythological',
  },
   {
    name: 'Spider-Man',
    description: 'A young hero with spider-like abilities.',
    overview: 'Peter Parker becomes Spider-Man after being bitten by a radioactive spider, fighting crime with his web-slinging and agility.',
    avatar: 'https://example.com/spiderman_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Wonder Woman',
    description: 'Amazonian princess with superhuman strength and combat skills.',
    overview: 'Diana of Themyscira is a warrior and ambassador of peace, wielding the Lasso of Truth and a magical sword.',
    avatar: 'https://example.com/wonder_woman_avatar.png',
    gender: 'Female',
    category: 'Superhero',
  },
  {
    name: 'Iron Man',
    description: 'Billionaire inventor and armored hero.',
    overview: 'Tony Stark uses his genius to build a high-tech suit of armor that gives him super strength and the ability to fly.',
    avatar: 'https://example.com/ironman_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Black Panther',
    description: 'King of Wakanda, protector of his people.',
    overview: 'T’Challa dons the mantle of Black Panther, using advanced technology and his enhanced abilities to defend Wakanda and the world.',
    avatar: 'https://example.com/black_panther_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Captain America',
    description: 'Super-soldier fighting for justice and freedom.',
    overview: 'Steve Rogers is enhanced to the peak of human potential and uses his shield to protect the innocent.',
    avatar: 'https://example.com/captain_america_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'The Flash',
    description: 'The fastest man alive.',
    overview: 'Barry Allen gains super-speed abilities, allowing him to travel through time and fight criminals with unparalleled agility.',
    avatar: 'https://example.com/flash_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Green Lantern',
    description: 'A member of the Green Lantern Corps, wielding a power ring.',
    overview: 'Hal Jordan uses a ring powered by willpower to create constructs and defend the universe from evil.',
    avatar: 'https://example.com/green_lantern_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Black Widow',
    description: 'Highly skilled assassin and spy.',
    overview: 'Natasha Romanoff is a former KGB agent turned Avenger, known for her combat skills and espionage expertise.',
    avatar: 'https://example.com/black_widow_avatar.png',
    gender: 'Female',
    category: 'Superhero',
  },
  {
    name: 'Doctor Strange',
    description: 'Master of the mystic arts.',
    overview: 'Stephen Strange becomes the Sorcerer Supreme, wielding magic to protect the world from mystical threats.',
    avatar: 'https://example.com/doctor_strange_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
  {
    name: 'Hawkeye',
    description: 'Master archer and marksman.',
    overview: 'Clint Barton is a highly skilled archer, known for his accuracy and combat abilities in the field.',
    avatar: 'https://example.com/hawkeye_avatar.png',
    gender: 'Male',
    category: 'Superhero',
  },
   {
    name: 'Joker',
    description: 'The Clown Prince of Crime.',
    overview: 'A sadistic mastermind and arch-nemesis of Batman, known for his chaotic nature and twisted sense of humor.',
    avatar: 'https://example.com/joker_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Lex Luthor',
    description: 'Genius billionaire and nemesis of Superman.',
    overview: 'Lex Luthor uses his intellect and wealth to try to destroy Superman and conquer the world.',
    avatar: 'https://example.com/lex_luthor_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Thanos',
    description: 'Mad Titan who seeks ultimate power.',
    overview: 'Thanos is a powerful being whose goal is to balance the universe by wiping out half of all life using the Infinity Gauntlet.',
    avatar: 'https://example.com/thanos_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Magneto',
    description: 'Master of magnetism and enemy of the X-Men.',
    overview: 'Magneto can control metal and uses his powers to fight against humanity, believing mutants are superior.',
    avatar: 'https://example.com/magneto_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Venom',
    description: 'Alien symbiote with a deep hatred for Spider-Man.',
    overview: 'Venom is a sentient alien symbiote that bonds with Eddie Brock, giving him powerful abilities to fight Spider-Man.',
    avatar: 'https://example.com/venom_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Harley Quinn',
    description: 'Psychotic criminal and lover of the Joker.',
    overview: 'Harley Quinn is a psychiatrist turned villainess, known for her chaotic and unstable personality.',
    avatar: 'https://example.com/harley_quinn_avatar.png',
    gender: 'Female',
    category: 'Villain',
  },
  {
    name: 'Green Goblin',
    description: 'Archenemy of Spider-Man and dangerous criminal mastermind.',
    overview: 'Norman Osborn becomes the Green Goblin after taking a serum that enhances his abilities but drives him insane.',
    avatar: 'https://example.com/green_goblin_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: "Ra's al Ghul",
    description: 'Leader of the League of Assassins.',
    overview: 'Ra’s al Ghul has access to the Lazarus Pit, making him immortal, and seeks to destroy civilization to “save” the Earth.',
    avatar: 'https://example.com/ras_al_ghul_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Loki',
    description: 'God of mischief and adopted brother of Thor.',
    overview: 'Loki uses his shapeshifting and illusionary powers to cause chaos, often trying to overthrow his brother Thor.',
    avatar: 'https://example.com/loki_avatar.png',
    gender: 'Male',
    category: 'Villain',
  },
  {
    name: 'Catwoman',
    description: 'Cat burglar with a complicated relationship with Batman.',
    overview: 'Selina Kyle is a skilled thief and acrobat with a complex moral code, sometimes helping and sometimes hindering Batman.',
    avatar: 'https://example.com/catwoman_avatar.png',
    gender: 'Female',
    category: 'Villain',
  },
   {
    name: 'Han Solo',
    description: 'Rebellious smuggler and hero of the Galactic Civil War.',
    overview: 'Han Solo is a former smuggler turned leader of the Rebel Alliance, piloting the Millennium Falcon.',
    avatar: 'https://example.com/han_solo_avatar.png',
    gender: 'Male',
    category: 'Sci-Fi',
  },
  {
    name: 'Princess Leia',
    description: 'Rebel leader and twin sister of Luke Skywalker.',
    overview: 'Leia Organa is a fearless leader of the Rebel Alliance and the daughter of Darth Vader.',
    avatar: 'https://example.com/princess_leia_avatar.png',
    gender: 'Female',
    category: 'Sci-Fi',
  },
  {
    name: 'Darth Vader',
    description: 'Former Jedi Knight turned Sith Lord.',
    overview: 'Anakin Skywalker becomes Darth Vader after falling to the dark side of the Force, serving as the right hand of Emperor Palpatine.',
    avatar: 'https://example.com/darth_vader_avatar.png',
    gender: 'Male',
    category: 'Sci-Fi',
  },
  {
    name: 'R2-D2',
    description: 'Astromech droid with a heroic side.',
    overview: 'R2-D2 is a resourceful droid who plays a key role in the Star Wars saga, often saving the day with his technical skills.',
    avatar: 'https://example.com/r2d2_avatar.png',
    gender: 'Robot',
    category: 'Sci-Fi',
  },
  {
    name: 'C-3PO',
    description: 'Protocol droid fluent in many languages.',
    overview: 'C-3PO is a humanoid robot designed to assist in etiquette, translation, and diplomacy.',
    avatar: 'https://example.com/c3po_avatar.png',
    gender: 'Robot',
    category: 'Sci-Fi',
  },
  {
    name: 'Boba Fett',
    description: 'Bounty hunter with a reputation for fearlessness.',
    overview: 'Boba Fett is one of the most feared bounty hunters in the galaxy, known for his combat prowess and Mandalorian armor.',
    avatar: 'https://example.com/boba_fett_avatar.png',
    gender: 'Male',
    category: 'Sci-Fi',
  },
  {
    name: 'The Doctor',
    description: 'Time-traveling alien with a fondness for saving worlds.',
    overview: 'The Doctor is a Time Lord from the planet Gallifrey, traveling through time and space to help those in need.',
    avatar: 'https://example.com/doctor_avatar.png',
    gender: 'Male/Female',
    category: 'Sci-Fi',
  },
  {
    name: 'Spock',
    description: 'Half-Vulcan, half-human science officer aboard the USS Enterprise.',
    overview: 'Spock serves as a logical and emotionless officer, offering wisdom and guidance on the Starship Enterprise.',
    avatar: 'https://example.com/spock_avatar.png',
    gender: 'Male',
    category: 'Sci-Fi',
  },
  {
    name: 'Ripley',
    description: 'Survivor of the xenomorphs in "Alien".',
    overview: 'Ellen Ripley is a strong and resourceful officer who battles alien creatures to save humanity.',
    avatar: 'https://example.com/ripley_avatar.png',
    gender: 'Female',
    category: 'Sci-Fi',
  },
  {
    name: 'WALL-E',
    description: 'Waste-collecting robot with a heart.',
    overview: 'WALL-E is a small robot left to clean Earth, who embarks on an adventure across the universe.',
    avatar: 'https://example.com/walle_avatar.png',
    gender: 'Robot',
    category: 'Sci-Fi',
  },
  ];

  for (const character of animeCharacters) {
    const exists = await prisma.dFTcharacter.findFirst({
      where: { name: character.name },
    });

    if (!exists) {
      await prisma.dFTcharacter.create({ data: character });
    }
  }

  console.log('Anime characters seeded!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
